Feature/BE/#65: 토큰 발급
boostcampwm2023/web03-LockFestival pull request #71
Opened 2023-11-15 17:26 UTC by JEM1224

## 🤷‍♂️ Description
- JWT로 토큰을 발급했어요 

## 📝 Primary Commits

- [X] jwt와 관련된 라이브러리 추가 
   - `@nestjs/jwt` : nestjs에서 jwt을 처리하기 위해 사용했어요.
   - `@nestjs/passport` :  passport 기능을 nestjs 생태계로 가져오기 위해 사용했어요.
   - `passport` : 사용자 인증을 간편화 하기 위해 사용했어요.
- [x] 엑세스 토큰과 리프레시 토큰 생성
   - `JwtService`를 주입하여 sign 메소드를 이용했어요.
   - sign의 매개변수에는 payload와 옵션을 설정해 jwt를 생성했어요.

## 📷 Screenshots
![image](https://github.com/boostcampwm2023/web03-LockFestival/assets/101504594/856c29be-de2b-4baf-8016-fb7b694e35c7)

2023-11-15 17:29 UTC, JEM1224 commented
토큰 인증하는 부분에서 에러가 자꾸 나서 이슈를 분리했습니다... !!

2023-11-15 17:31 UTC, JEM1224 commented on backend/src/modules/authModules/auth/auth.service.ts
> +  async getAccessToken(payload: { username: string }) {
payload을 뭘로 정하면 좋을까요???

2023-11-16 03:24 UTC, Capoomaru commented on backend/src/modules/authModules/auth/auth.service.ts
> +  async getAccessToken(payload: { username: string }) {
`nickname`, `username` 정도 들어가면 될 것 같아요!
권한도 들어가면 좋을 것 같은데 저희 서비스에 권한으로 쓸 데이터가 없어서 이정도가 적당할 것 같아요!

2023-11-16 03:32 UTC, Capoomaru requested changes
실행 불가능한 상태여서 `reject` 드립니다 🙏
필요한 커밋들 추가해주세요!!

2023-11-16 03:32 UTC, Capoomaru commented on backend/src/modules/authModules/auth/auth.service.ts
> +        expiresIn: `${this.configService.get('JWT_ACCESS_TOKEN_TIME')}s`,
단위까지 같이 `.env`에 작성해도 될 것 같아요!

2023-11-16 03:32 UTC, Capoomaru commented on backend/src/modules/authModules/auth/auth.module.ts
> +import { JwtStrategy } from '@auth/jwt.strategy';
alias path로 잘 적용해주신 점 좋네요 👍

2023-11-16 03:32 UTC, Capoomaru commented on backend/src/modules/authModules/auth/auth.module.ts
> +import { JwtStrategy } from '@auth/jwt.strategy';
빠진 `JwtStratege` 함께 커밋해주세요 :)

2023-11-16 05:03 UTC, JEM1224 commented on backend/src/modules/authModules/auth/auth.module.ts
> +import { JwtStrategy } from '@auth/jwt.strategy';
넵!

2023-11-16 07:27 UTC, Capoomaru approved these changes
에러 수정하시느라 고생하셨습니다!!
![images](https://github.com/boostcampwm2023/web03-LockFestival/assets/44056518/c53d79e8-16f7-4123-86a3-af70680c34f4)

2023-11-16 07:27 UTC, Capoomaru commented on backend/src/modules/authModules/auth/auth.service.ts
> +        expiresIn: `${this.configService.get('JWT_ACCESS_TOKEN_TIME')}`,
빠른 반영 좋습니다 💯

2023-11-16 07:27 UTC, Capoomaru commented on backend/src/modules/authModules/auth/jwt.strategy.ts
> +      ignoreExpiration: true,
해당 부분은 인증 처리 과정이 추가되고나면 수정을 고민해봐야할 것 같네요!
Expiration이 만료되면 에러처리를 하는 것이 맞을 것 같아요!

2023-11-16 08:10 UTC, merged