Feature/FE/#45: 로그인 모달, 회원가입 모달 구현 / 네아로 구현중 API 연동 필요
boostcampwm2023/web03-LockFestival pull request #97
Opened 2023-11-21 13:59 UTC by seonye-98

## 🤷‍♂️ Description

- 임시로 회원가입 버튼을 만들었어요.
- 네이버 로그인 API는 완벽하게 연동은 되어있지 않고, msw로도 안되는 상황이에요. 오류는 나지 않아서 일단 합쳐서 같이 해결할 예정이에요.
- 회원가입 모달은 닉네임 중복확인, 회원가입 요청 API만 연동되어 있지 않고 나머지 기능은 완료한 상태에요.
- 버튼 컴포넌트에 disabled일때의 스타일을 추가했어요.
- 추가 설명은 Screenshots에서 할게요.

## 📝 Primary Commits

- [x] 검색 바 블러 이벤트 적용
- [X] 로그인 모달 마크업 및 네이버 로그인 API 일부 구현
- [x] 회원가입 모달 구현 (API 연동 x)

## 📷 Screenshots
1. 로그인 로그아웃
    - 로그인시 한번에 프로필 사진이 바뀌지 않아요.
    - 프로필 클릭하면 로그아웃되게 일단 구현했어요.

https://github.com/boostcampwm2023/web03-LockFestival/assets/82202370/6d37eea0-32ac-4b1f-b35e-ec6c4affacc9

2. 회원가입 모달
    - 테마 사진 렌더링이 느려요.
    - 중복확인, 완료에 API 연동 안되어있어요.
    - 닉네임을 입력하지 않거나 선호하는 카테고리를 선택하지 않는 경우 NEXT, 완료 버튼이 비활성화 되게 했어요.

https://github.com/boostcampwm2023/web03-LockFestival/assets/82202370/6c818a9d-55be-4708-9968-6cb6c985ce42

3. 검색바 블러 이벤트

https://github.com/boostcampwm2023/web03-LockFestival/assets/82202370/3f772256-2ae9-4d36-8e71-775a53f856e3

2023-11-21 14:23 UTC, teihong93 reviewed
슬쩍 지나갑니다

2023-11-21 14:29 UTC, seonye-98 commented
> 슬쩍 지나갑니다

감사합니다!

2023-11-21 14:29 UTC, seonye-98 commented on frontend/src/components/Header/HeaderRest/HeaderRest.tsx
>    const [isClickSearchButton, setIsClickSearchButton] = useState<boolean>(false);
제가 구현한 부분은 아니지만 검색 버튼을 클릭했을때 입력창이 나타나는데 필요한 state인 것 같습니다! 가상선택자로 할 수 있을까요?

2023-11-21 15:05 UTC, teihong93 commented on frontend/src/components/Header/HeaderRest/HeaderRest.tsx
>    const [isClickSearchButton, setIsClickSearchButton] = useState<boolean>(false);
아 입력창이 나타나야 하는거면 state가 필요할 수 있겠네요

2023-11-21 15:24 UTC, navyjeongs requested changes
많은 기능을 구현하셨네요!! 배워갑니다

2023-11-21 15:24 UTC, navyjeongs commented on frontend/index.html
> +      charset="utf-8"
혹시 해당 스크립트가 필요한 이유가 있을까요??
저희는 백엔드에서 토큰을 발급받아서 sdk가 필요없을 것 같아서요!!

2023-11-21 15:24 UTC, navyjeongs commented on frontend/src/__mocks__/handlers/profileHandlers.ts
> +    if (localStorage.getItem('com.naver.nid.access_token')) {
저희가 가지고 있는 토큰은 네이버 토큰이 아니라 저희 서버 accessToken이라서 이 부분이 추후에 변경되어야 할 것 같아요

2023-11-21 15:24 UTC, navyjeongs commented on frontend/src/components/Header/HeaderRest/HeaderRest.tsx
> +              autoFocus
autoFocus라는게 있군요 배워갑니다!!

2023-11-21 15:24 UTC, navyjeongs commented on frontend/src/components/Header/HeaderRest/HeaderRest.tsx
> +              window.location.replace('/');
이렇게하면 새로고침이 일어나서 새로고침말고 다른 방법을 찾아봐야할 것 같아요!!

2023-11-21 15:24 UTC, navyjeongs commented on frontend/src/components/Header/HeaderRest/HeaderRest.tsx
> +          <>회원가입</>
저희가 자체 회원가입이 없기 때문에 회원가입 버튼을 없애고 로그인 버튼을 누르면 네이버로 로그인을 띄우면 될 것 같은데 어떻게 생각하세요??

2023-11-21 15:24 UTC, navyjeongs commented on frontend/src/components/JoinModal/JoinModalComponent/JoinModalComponent.tsx
> +            console.log(nameInput, selectGenre);
TODO라서 그렇겠지만 나중에 console 제거해주세요!

2023-11-21 15:24 UTC, navyjeongs commented on frontend/src/components/LoginModal/NaverLogin/NaverLogin.tsx
> +  }, []);
앞서말씀드렸지만 저희가 액세스 토큰을 발급받지 않고 코드를 발급받아 서버로 넘겨주는 경우라서 아마 없어도 될 것같아요!!

혹시 제가 잘못된 정보로 알고 있으면 알려주세요!!

2023-11-21 15:40 UTC, seonye-98 commented on frontend/index.html
> +      charset="utf-8"
정석님이 말씀해주신것처럼 바로 access token을 발급받기 위함인가봐요ㅠ

2023-11-21 15:41 UTC, seonye-98 commented on frontend/src/components/Header/HeaderRest/HeaderRest.tsx
> +              window.location.replace('/');
넵!!

2023-11-21 15:42 UTC, seonye-98 commented on frontend/src/components/Header/HeaderRest/HeaderRest.tsx
> +          <>회원가입</>
PR 젤 첫번째 줄에도 적었는데, 회원가입 버튼은 회원 가입 모달 확인하기 위해서 임시로 추가한 버튼입니다!

2023-11-21 15:43 UTC, seonye-98 commented on frontend/src/components/LoginModal/NaverLogin/NaverLogin.tsx
> +  }, []);
ㅠㅜ내일 같이 해결해봐유

2023-11-22 01:57 UTC, navyjeongs approved these changes
LGTM ✅

2023-11-22 01:57 UTC, merged